// This file is automatically generated by vscode-react-native@0.2.5
// Please do not modify it manually. All changes will be lost.
try {
    var path = require("path");
    var Launcher = require("/Users/moshef/.vscode/extensions/vsmobile.vscode-react-native-0.2.5/out/debugger/launcher.js").Launcher;
    new Launcher("/Users/moshef/Documents/projects/tests/react-native/AwesomeProject", "/Users/moshef/Documents/projects/tests/react-native/AwesomeProject").launch();
} catch (e) {
    throw new Error("Unable to launch application. Try deleting .vscode/launchReactNative.js and restarting vscode.");
}